# Secret Management and Rotation Workflow
# Demonstrates: Vault, AWS Secrets Manager, Azure Key Vault
# Use case: Automated secret rotation across multiple secret stores

name: Multi-Cloud Secret Rotation
description: Rotate database credentials across Vault, AWS Secrets Manager, and Azure Key Vault
version: "1.0"

trigger:
  type: schedule
  schedule: "0 0 * * 0"  # Weekly on Sunday at midnight

nodes:
  # Generate new secure password
  - id: generate_password
    type: test_data_generator
    parameters:
      operation: generate_secure_password
      length: 32
      include_special_chars: true

  # Read current secret from HashiCorp Vault
  - id: read_vault_secret
    type: vault
    parameters:
      operation: read_secret
      vault_url: "https://vault.example.com:8200"
      path: "database/prod/credentials"
      mount: "secret"

  # Update secret in Vault
  - id: update_vault_secret
    type: vault
    parameters:
      operation: write_secret
      vault_url: "https://vault.example.com:8200"
      path: "database/prod/credentials"
      mount: "secret"
      data:
        username: "{{nodes.read_vault_secret.output.data.username}}"
        password: "{{nodes.generate_password.output.password}}"
        rotated_at: "{{workflow.execution_time}}"
        previous_password: "{{nodes.read_vault_secret.output.data.password}}"
    depends_on:
      - read_vault_secret
      - generate_password

  # Store in AWS Secrets Manager
  - id: update_aws_secret
    type: aws_secrets_manager
    parameters:
      operation: update_secret
      secret_name: "prod/database/credentials"
      secret_value:
        username: "{{nodes.read_vault_secret.output.data.username}}"
        password: "{{nodes.generate_password.output.password}}"
      description: "Rotated on {{workflow.execution_time}}"
    depends_on:
      - generate_password

  # Create new version in Azure Key Vault
  - id: update_azure_secret
    type: azure_key_vault
    parameters:
      operation: set_secret
      vault_url: "https://mykeyvault.vault.azure.net"
      secret_name: "database-credentials"
      value: "{{nodes.generate_password.output.password}}"
      content_type: application/json
      tags:
        rotated_at: "{{workflow.execution_time}}"
        rotated_by: "workflow"
    depends_on:
      - generate_password

  # Update actual database password
  - id: update_database
    type: database
    parameters:
      operation: execute
      query: "ALTER USER {{nodes.read_vault_secret.output.data.username}} WITH PASSWORD '{{nodes.generate_password.output.password}}'"
    depends_on:
      - update_vault_secret
      - update_aws_secret
      - update_azure_secret

  # Verify new credentials work
  - id: verify_credentials
    type: database
    parameters:
      operation: query
      query: "SELECT 1"
      connection_string: "postgresql://{{nodes.read_vault_secret.output.data.username}}:{{nodes.generate_password.output.password}}@localhost/prod"
    depends_on:
      - update_database

  # Read metadata from all secret stores for audit
  - id: audit_vault
    type: vault
    parameters:
      operation: read_kv_metadata
      vault_url: "https://vault.example.com:8200"
      path: "database/prod/credentials"
      mount: "secret"
    depends_on:
      - verify_credentials

  - id: audit_aws
    type: aws_secrets_manager
    parameters:
      operation: describe_secret
      secret_name: "prod/database/credentials"
    depends_on:
      - verify_credentials

  - id: audit_azure
    type: azure_key_vault
    parameters:
      operation: get_secret
      vault_url: "https://mykeyvault.vault.azure.net"
      secret_name: "database-credentials"
    depends_on:
      - verify_credentials

  # Log rotation event
  - id: log_rotation
    type: logging
    parameters:
      level: info
      message: "Secret rotation completed successfully"
      metadata:
        vault_version: "{{nodes.audit_vault.output.metadata.current_version}}"
        aws_version: "{{nodes.audit_aws.output.version_id}}"
        azure_version: "{{nodes.audit_azure.output.version}}"
        rotated_at: "{{workflow.execution_time}}"
    depends_on:
      - audit_vault
      - audit_aws
      - audit_azure

  # Send CloudWatch metric
  - id: emit_metric
    type: metrics
    parameters:
      operation: emit
      metric_name: "secret_rotation_success"
      value: 1
      unit: "count"
      dimensions:
        environment: "production"
        secret_type: "database"
    depends_on:
      - verify_credentials

  # Notify security team
  - id: notify_security
    type: slack
    parameters:
      operation: send_message
      channel: "#security-ops"
      text: "Database credentials rotated successfully across all secret stores"
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: |
              *Secret Rotation Complete* ✅

              • Vault version: {{nodes.audit_vault.output.metadata.current_version}}
              • AWS version: {{nodes.audit_aws.output.version_id}}
              • Azure version: {{nodes.audit_azure.output.version}}
              • Rotated at: {{workflow.execution_time}}
    depends_on:
      - log_rotation

on_error:
  # Rollback on failure
  - id: rollback_notification
    type: pagerduty
    parameters:
      operation: create_incident
      title: "Secret rotation failed - manual intervention required"
      urgency: high
      body:
        type: incident_body
        details: "Failed to rotate database credentials. Previous password may still be active."
